Feature/add page layout
raffal1993/project-storefront-freshcart-bootstrap pull request #3
Opened 2023-01-17 22:17 UTC by raffal1993

2023-01-18 20:14 UTC, gradzio requested changes

2023-01-18 20:14 UTC, gradzio commented on src/app/components/footer/footer.component.html
> +                ><img src="../assets/images/payment/paypal.svg" alt=""
it is better to use absolute paths, it might stop working when you put it on github pages

2023-01-19 17:24 UTC, raffal1993 commented on src/app/components/footer/footer.component.html
> +                ><img src="../assets/images/payment/paypal.svg" alt=""
changes pushed, hope now it's good

2023-01-20 02:44 UTC, gradzio approved these changes

2023-01-20 02:44 UTC, merged